export const SET_USER_ID       = 'USER/SET_USER_ID';
export const CONFIRMATION_CODE_SUCCESS       = 'USER/CONFIRMATION_CODE_SUCCESS';
export const CONFIRMATION_CODE_REQUEST       = 'USER/CONFIRMATION_CODE_REQUEST';
export const CONFIRMATION_CODE_FAILURE       = 'USER/CONFIRMATION_CODE_FAILURE';
export const CLEAR_ERROR       = 'USER/CLEAR_ERROR';
export const CANCEL_CONFIRMATION       = 'USER/CANCEL_CONFIRMATION';
export const LOGIN_SUCCESS       = 'USER/LOGIN_SUCCESS';
export const LOGIN_REQUEST       = 'USER/LOGIN_REQUEST';
export const LOGIN_FAILURE       = 'USER/LOGIN_FAILURE';
export const LOGIN_LOGOUT        = 'USER/LOGIN_LOGOUT';
export const CHANGE_MAKETS_STATUS = 'MAKETS/CHANGE_MAKET_STATUS';
export const MAKETS_SGRID_PAGE_CHANGE_PARAMS = 'MAKETS/MAKETS_SGRID_PAGE_CHANGE_PARAMS';
export const MAKETS_FILTER_CHANGE  = 'MAKETS/MAKETS_FILTER_CHANGE';
export const MAKETS_SORT_CHANGE    = 'MAKETS/MAKETS_SORT_CHANGE';
export const MAKETS_REQUEST        = 'MAKETS/MAKETS_REQUEST';
export const MAKETS_SUCCESS        = 'MAKETS/MAKETS_SUCCESS';
export const MAKETS_FAILURE        = 'MAKETS/MAKETS_FAILURE';
export const MAKETS_UPDATE_STATUS_REQUIRED      = 'MAKETS/MAKETS_UPDATE_STATUS_REQUIRED';





